Changes to properly support Mutexes on NET6.0
mbdavid/LiteDB pull request #2206
Opened 2022-06-24 13:34 UTC by conradmicallef

Global Mutexes were being created without insufficient rights for a 2nd process running on same machine to use them

This fix addresses that by using same methodology applied to NETFRAMEWORK but to NET6.0

2023-01-12 11:47 UTC, inbarbarkai commented
Is there any plan on merging this PR?

2023-10-20 19:55 UTC, tjmoore commented
Any update? What's the symptom without this fix, is there an particular error raised?

Looking for solutions to access denied errors on shared mode access, but I'm not seeing it on the mutex but on the journal file (and only one process is writing, the other opens database in read mode).

2024-06-04 19:10 UTC, JKamsker commented
I would also like to see some repro code before merging this.

2024-06-05 05:48 UTC, inbarbarkai commented
@JKamsker I can't provide a repro, but I can provide the scenario.

Environment: Windows 10/11
Version: 5.0.12

2 writer processes from different users.
1 of the writers is also a reader.

This happened sometimes during our tests, but our customers encountered it all the time, forcing us to release a patch disabling some functionalities.
We replaced it with SQLite to restore those functionalities.

2024-06-05 06:12 UTC, JKamsker commented
@inbarbarkai Oh i remember now, i had a similar problem with named pipes and different users.

Ok thank you for the clarification! I will try to get to it asap :)

2024-06-05 18:02 UTC, tjmoore commented
Similar to above, have not reproduced the issues we see, but have had them from customers, particularly this kind of error.

`System.IO.IOException: The process cannot access the file 'C:\\XXX\\somedatabase.db' because it is being used by another process.`

This occurs either on .db or the log, and the processes all open the database in shared mode. Have tried long and short lived instances of LiteDatabase also (I believe in shared mode it is internally opening and closing connections on each operation so likely makes little difference, unlike direct mode).

We've done extensive diagnostics and cannot see what the other process is. Some customers show signs of things like Microsoft Defender for Endpoints (the corporate version of Defender) access files but looks more like it detecting file access not actually opening and locking files. Other customers don't have anything like this though.

Any solution needs to be proven fix to roll out to customers though as already got frustrated customers, hence repo is very desirable.

Only alternative have thought about is to move to a single process for database operations and some communication between them. Getting into building a database server territory though and already considering supporting MongoDB as an alternative to LiteDB.

2024-06-07 23:17 UTC, JKamsker requested changes

2024-06-07 23:17 UTC, JKamsker commented on LiteDB/Client/Shared/SharedEngine.cs
>              catch (NotSupportedException ex)
Big nope! Please make it more readable.

2024-06-07 23:17 UTC, JKamsker commented on LiteDB/LiteDB.csproj
> +    <TargetFrameworks>netstandard1.3;netstandard2.0;net6.0</TargetFrameworks>
We are not going to add or drop support for any TargetFrameworks just yet ;)

2024-06-07 23:22 UTC, JKamsker commented
I am not sure about the added dependencies. 
about the framework change: we are currently internally thinking about following the official microsoft support matrix.

2024-07-30 18:04 UTC, jobrien9 commented
Hi all - Is there any update regarding following the Microsoft support matrix? I'd love to add .NET 8 support if that's allowed. I was able to get this working locally for my  .NET 8 applications using [the code from this related issue](https://github.com/mbdavid/LiteDB/issues/2439), but I would be happy to help get this merged if I can.

2025-10-08 16:18 UTC, JKamsker commented
Replaced by https://github.com/litedb-org/LiteDB/pull/2711

2025-10-08 16:18 UTC, closed without merging