Deserialize dictionary key with TypeDescriptor
mbdavid/LiteDB pull request #2568
Opened 2024-11-22 02:07 UTC by Joy-less

`BsonDocument` only supports `string` keys. Since `Dictionary` is serialized as `BsonDocument`, certain types don't work as keys.

This pull request converts the keys to the correct type when deserializing, using the method in #588.

For example, the key `d396d0e8-2763-4ad6-a1c0-f19f254576ec` can now be deserialized as a `Guid`.

This isn't really ideal but it does the job.

Fixes #546 and #2161. Replaces #588.

2024-12-01 21:49 UTC, JKamsker commented
Hi @Joy-less 

Great job on the changes! Could you also implement and ensure the following works as expected?

```csharp
public class DataContainer
{
    public Dictionary<(int, string), string> DataDict { get; set; }
}
```

Additionally, as mentioned earlier on Discord, reviewing a PR becomes challenging when it includes unrelated changes (e.g., refactor-renames). For future submissions, keeping PRs focused on a single purpose would help simplify the review process.

Thank you for your efforts on this!

2024-12-01 22:43 UTC, Joy-less commented
> Would it be possible to also implement and ensure the following works as expected?
> 
> ```cs
> public class DataContainer
> {
>     public Dictionary<(int, string), string> DataDict { get; set; }
> }
> ```

This does not work as expected. The key should be serialized as JSON for something complex like this. However, that would break compatibility, so it might be a good idea to assume it's a string key if it fails to deserialize as JSON.

2024-12-01 23:37 UTC, Joy-less commented
I've changed the pull request to serialize the key as JSON if it's not a string.
One of the tests was failing because of how LiteDB truncates DateTimes to the nearest millisecond. To keep `JsonSerializer` consistent with `BufferWriter`, I changed the test so now it accepts the truncated value as well.
All tests passed now.

2024-12-01 23:47 UTC, JKamsker commented
@Joy-less 
Thanks for the changes! 
Can you think of an scenario where the deserialization doesnt work on databases created with a prior (released) version of litedb?

2024-12-02 01:05 UTC, JKamsker commented on LiteDB/Client/Mapper/BsonMapper.Serialize.cs
> +                    ?? JsonSerializer.Serialize(Serialize(entry.Key));
```csharp
TupleDict = new()
  {
      [(2, "xxx")] = "test",
  },
  ```
from the tests produces
```csharp
System.ValueTuple`2[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib
```

2024-12-02 01:05 UTC, JKamsker requested changes

2024-12-02 01:05 UTC, JKamsker commented on LiteDB/Client/Mapper/BsonMapper.Serialize.cs
> +                    ?? JsonSerializer.Serialize(Serialize(entry.Key));
```csharp
TupleDict = new()
  {
      [(2, "xxx")] = "test",
  },
  ```
from the tests produces
```csharp
System.ValueTuple`2[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib
```

2025-09-23 20:28 UTC, closed without merging